# Generated by Django 4.2.3 on 2023-07-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_room_topic_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='topics',
        ),
    ]
