# Generated by Django 4.2.3 on 2023-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_topic_room_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
