# Generated by Django 4.2.3 on 2023-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
