# Generated by Django 4.2.3 on 2023-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_downvotes_alter_room_upvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reply_to',
            new_name='replyto',
        ),
    ]
